### PR TITLE
Feature/zero suppression wrap

### PR DESCRIPTION
**Pull request by rodwyer100**
Changes to allow for Zero Suppression

 Some code in the include file as well as in GEMUnpacker.h. The changes facilitate the wrapping required in zero suppression vfat payloads by reading in directly from the stream, so there are enough structural changes that I would suggest the creation of a new repository in the main branch. 

This is also because this has yet to be tested with firmware, but the creator (me) will soon be leaving and this push request ought to be made so that a couple weeks work doesn't have to be reduplicated.

 Furthermore changes that are required to avoid length errors in the AMC_Header (which have been observed with our current, not zero-suppression enabled, software are not implemented in this version, but they easily can be upon request.

The nature of these changes are not too drastic, but certainly require introduction to the not initiated. Therefore I have included some of the presentations I have made in GEMDAQ software meetings, which should include the required knowledge about how various suppression modes send data payloads and how my new software handles them.

 Any unaddressed topics I can probably field if you respond to this. Finally, this software will be tested in tandem with relevant firmware, which hasn't been completed yet.

[TuesdayVFAT2.pptx](https://github.com/cms-gem-daq-project/gem-light-dqm/files/3500320/TuesdayVFAT2.pptx)
[TuesdayVFAT.pptx](https://github.com/cms-gem-daq-project/gem-light-dqm/files/3500321/TuesdayVFAT.pptx)

### CODE REVIEW

**Comment by bdorney** [comment]
Target branch doesn't seem correct.  Are you sure you branched from the correct point?

**Comment by bdorney** [comment]
Also please fill out the PR template when submitting a PR.

**Comment by rodwyer100** [comment]
The branch I have chosen was arbitrary because the branch I want doesn't exist (i.e. I think needs to be created). The reason I believe this is merited is that before we get the firmware required developed, I believe it is in our best interest to not affect our permanent copy of v3.

I apologize for not filing out a template. Would you prefer continuing instead with a wholly new PR? Ultimately I think a new branch in the main repository should be created to hold, for while I think it needs to be accessible to everyone and ultimately incorporated into master, right now I don't want to affect anything that is working without testing w/ Evaldas' firmware. Similarly, I also don't want it to fade into obscurity.

**Comment by mexanick** [comment]
Please re-submit your PR to the `develop` branch and fill out the template correctly.

**Pull request closed without merging**
